---
title: "Classification example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r load_libraries}
library(tidyverse)
library(here)
library(ggthemes)
library(gridExtra)

select <- dplyr::select
```


```{r load_tr_data}


train <- read.csv(here("data", "2022", "training.csv"))

train <- train |> 
  filter(col1 >= 1)

axis <- seq(925, 5010, by = 5)
```





```{r abs}
# Convert to absorbance
train[, 2:1061] <- log10(1 / train[, 2:1061])
```





```{r plot_tr_data}

ind <- sample(3244, 300)

p1 <- train[ind, ] |>
  mutate(id = 1:nrow(train[ind, ]), Diet = as.factor(Diet)) |>
  pivot_longer(col1:col1060) |>
  mutate(name = as.numeric(str_remove(name, "col"))) |>
  ggplot(aes(x = name, y = value, group = id, col = Diet)) +
  geom_line(aes(alpha = 0.2)) +
  scale_colour_colorblind() +
  ylab("Absorbance") +
  xlab("") +
  scale_x_continuous(breaks = seq(0, 1060, by = 53 * 2), labels = as.character(round(seq(min(axis), max(axis), length.out = length(seq(0, 1060, by = 53 * 2)))))) +
  theme_classic() +
  guides(alpha = "none")
```

```{r}


x_train <- train[, 2:1061]


mn <- apply(x_train, 2, mean)
sd <- apply(x_train, 2, sd)

x_train <- sweep(x_train, 2, mn, "-")
x_train <- sweep(x_train, 2, sd, "/")


ac_region <- c(0:173, 206:537, 720:751)
ac_region_plus <- c(ac_region, 205, 556, 952)
x_train <- x_train[, ac_region_plus]
```




```{r create_tibble}
astib_tr <- as_tibble(x_train)
astib_tr <- astib_tr |> mutate(Diet = as.factor(train$Diet))
```

```{r}
library(MASS)

z <- lda(Diet ~ ., astib_tr, prior = c(1, 1, 1) / 3)


lda_tr <- as_tibble(as.matrix(x_train) %*% z$scaling)
lda_tr <- lda_tr |> mutate(Diet = astib_tr$Diet)


p2 <- lda_tr |>
  ggplot(aes(x = LD1, y = LD2, col = Diet)) +
  geom_point(alpha = 0.5) +
  scale_colour_colorblind() +
  ylim(c(-5, 5))
```


```{r}
p1
p2
```

